### PR TITLE
feat: optimize website

### PR DESCRIPTION
**Pull request by Tragio**
Hi there 👋,

I noticed some opportunities for improvement on the website and took a little of my time to contribute 🚀.

- 📉 Stackblitz now only loads when in view, reducing the initial load size from 1.5MB to 0MB.
- 🎨 FontAwesome was replaced by IcoMoon to load only the necessary icons, reducing file size from 541kb to 2kb.
- 🖼️ Images are now lazy-loaded, and `alt` attributes were added where needed.
- 🔠 Fonts were simplified, self-hosted, and preloaded for faster access.
- 🌐 The header image was converted to `.webp` format and preloaded.
- 🖼️ The support section now uses a `.jpg` as an inline image instead of a background image, enabling lazy-loading (background images always load by default).
- ✂️ Some `.svg` images were minified for better performance.
- 📊 Google Analytics was replaced by [Minimal Analytics](https://minimalanalytics.com/) for lighter tracking, reducing file size from 73kb to 1.5kb.
- ⏸️ Plyr was deactivated since it wasn’t in use.
- 🔗 Links were updated with `rel="noopener"` for enhanced security.
- 📝 `document.write` was replaced to handle the copyright year.
- ⚙️ Parcel upgraded to version 2.

Requests were reduced from ~135 to 26, and the total size went from 6.7MB to 270KB. 🎉

Of course, additional improvements could be made, but I’ve tried to keep the changes as minimal as possible. For future reference, here are a few suggestions:
- CSS could be reviewed or even converted to Tailwind, given the simplicity of the site.
- PNG/JPG images could be converted to WebP/AVIF formats for better performance.
- The Open Collective fetch could be made static with a cron job to periodically update it.
- Making images and fonts static assets (avoiding hashing) would help maintain cache consistency across builds.

Hope these changes help! Let me know if there’s anything further to address.

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
The build is now failing with the following error:

image

**Comment by Tragio** [comment]
Hi @kamilmysliwiec 👋 

Thank you for the quick heads up. I already fixed it 🙂

**Comment by kamilmysliwiec** [comment]
Now:

image

Before:

image

Note:
- wrong font-weight (in a few sections)
- icon size (source code button)

**Comment by kamilmysliwiec** [comment]
I cherry-picked most of the changes you made, thanks!

**Comment by Tragio** [comment]
Hello @kamilmysliwiec 👋

Sorry for not doing the changes, I'm on holidays 😋

Thank you very much for the attention and the time for this PR. 🙏

**Pull request merged**
