### PR TITLE
fix footer

### PR DESCRIPTION
**Pull request by Arhell**
fix issue https://github.com/nestjs/nestjs.com/issues/43

### CODE REVIEW

**Comment by Arhell** [comment]
cc @kamilmysliwiec
after fix
too much padding, after fixing the content is more centered and there is no scrolling

**Comment by kamilmysliwiec** [comment]
I'm not sure how changing the `padding` value would address this issue. The `page-footer` element has `box-sizing: border-box;` which means that setting padding won't affect its overall width (in this case).

**Comment by Arhell** [comment]
> I'm not sure how changing the `padding` value would address this issue. The `page-footer` element has `box-sizing: border-box;` which means that setting padding won't affect its overall width (in this case).

You are right, but the footer already has padding in the container, because of this, at 768 it is 40 pixels (this amount on both sides) + 30 pixels for the container and its 750 width gives more than 768 and because of this a little scrolling appears + content is not strongly centered.

Try to look at the container in 768 in the browser and see that it is shifted to the right on the main site https://nestjs.com/

**Comment by kamilmysliwiec** [comment]
Makes sense! Thanks

**Pull request merged**
